### ISSUE TITLE
Youtube Video playing is not good on Chromium in rk-rootfs-build (77cba1d git)

### ISSUE THREAD

**Issue by ertos12** [rockchip-linux/rk-rootfs-build#48]
I built and installed Debian 9 (stretch) on the rk3288 board using the latest contents (77cba1d) of the rk-rootfs-build repository. Compared to the previous version (57f157a) of rk-rootfs-build, the video image play function is greatly improved. However, the performance of Chromium is very unsatisfactory. When you access the Youtube site from the current version of Chromium and run the video, the screen is cut off and slows down, so you can hardly see the video. Currently installed Chromium is chromium_79.0.3945.130-1 ~ deb10u1_armhf. Chromium_67.0.3396.87-1 ~ deb9u1_armhf was installed in the rk-rootfs-build of the previous version (57f157a), and the FHD video was executed in full screen, but there was little interruption or slowdown, and the screen was in good condition. I tried installing chromium_67.0.3396.87 of the old version (57f157a) rk-rootfs-build in the current version (77cba1d), but it does not run. The difference between the two versions is that chromium was included in the package in the previous version (57f157a), and in the current version (77cba1d), it is installed directly with the apt command from the repository. Check the problem and ask chromium for package support.

**Comment by JeffyCN** [comment]
we've supported ffmpeg HW video decoding for chromium recently, so the chromium needs to disable sandbox for accessing HW device, try:
https://github.com/rockchip-linux/rk-rootfs-build/commit/a15ccc65a6560bcd69d277e6556fcf6be880daee

**Comment by JeffyCN** [comment]
it still not perfect since there's an extra frame conversion(using RGA HW 2D accel) from NV12 to YUV420P.

we have a better solution but requires the users to modify and recompile chromium:
https://github.com/JeffyCN/libv4l-rkmpp
https://github.com/JeffyCN/meta-rockchip/tree/master/dynamic-layers/recipes-browser/chromium/chromium-ozone-wayland_83.0.4103  <-- only the VDA patches, and that should be the same for x11 version
